[build]
  publish = "client/build"
  command = "npm ci --legacy-peer-deps && npm run install:all && cd client && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
