# Set the base directory to the repository root
# This overrides any conflicting UI settings.
[build]
  base    = "/" 
  publish = "client/build"
  # Use the isolated build script that completely avoids workspace conflicts
  command = "node build-netlify-isolated.js"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9" # Specifying NPM version is good practice
  CI = "false" # Often helps with create-react-app builds
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  GENERATE_SOURCEMAP = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_FORCE = "false"
  NPM_CONFIG_WORKSPACES = "false"  # Disable workspaces
  NPM_CONFIG_WORKSPACE = "false"   # Additional workspace disable
  # TypeScript version resolution
  NPM_CONFIG_OVERRIDES = "typescript@4.9.5"
  NPM_CONFIG_RESOLUTIONS = "typescript@4.9.5"
  # Additional npm configuration for workspace issues
  NPM_CONFIG_INCLUDE_WORKSPACE_ROOT = "false"

# Your redirects remain the same
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health-check"
  status = 200

[[redirects]]
  from = "/api/registration-status"
  to = "/.netlify/functions/registration-status"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login-db"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register-db"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/messages/:splat"
  to = "/.netlify/functions/messages-conversation/:splat"
  status = 200

[[redirects]]
  from = "/api/message"
  to = "/.netlify/functions/message"
  status = 200

[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/conversation/:splat"
  to = "/.netlify/functions/conversation/:splat"
  status = 200

[[redirects]]
  from = "/api/security/info"
  to = "/.netlify/functions/security-info"
  status = 200

[[redirects]]
  from = "/api/system/status"
  to = "/.netlify/functions/system-status"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
