[build]
  publish = "client/build"
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health-check"
  status = 200

[[redirects]]
  from = "/api/health-check"
  to = "/.netlify/functions/health-check"
  status = 200

[[redirects]]
  from = "/api/registration-status"
  to = "/.netlify/functions/registration-status"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login-db"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register-db"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/messages/*"
  to = "/.netlify/functions/messages-conversation/:splat"
  status = 200

[[redirects]]
  from = "/api/message"
  to = "/.netlify/functions/message"
  status = 200

[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/conversation/*"
  to = "/.netlify/functions/conversation"
  status = 200

[[redirects]]
  from = "/api/security/info"
  to = "/.netlify/functions/security-info"
  status = 200

[[redirects]]
  from = "/api/system/status"
  to = "/.netlify/functions/system-status"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
