# Netlify Configuration for Crypto 512 Secure Communication App
[build]
  base = "client"
  publish = "client/build"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_OPTIONS = "--max-old-space-size=4096"
  GENERATE_SOURCEMAP = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  directory = "netlify/functions"

# API redirects
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health-check"
  status = 200

[[redirects]]
  from = "/api/registration-status"
  to = "/.netlify/functions/registration-status"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/conversation/:splat"
  to = "/.netlify/functions/conversation/:splat"
  status = 200

[[redirects]]
  from = "/api/security/info"
  to = "/.netlify/functions/security-info"
  status = 200

[[redirects]]
  from = "/api/system/status"
  to = "/.netlify/functions/system-status"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
